# Generated by Django 3.2.9 on 2021-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('fleet_type', models.CharField(blank=True, max_length=20)),
                ('fleet_model', models.CharField(blank=True, max_length=10)),
                ('station', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
