# Generated by Django 3.2.9 on 2021-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_from', models.CharField(max_length=30)),
                ('trip_to', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
